//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется metabolograf.rc
//
#define IDCANCEL2                       3
#define ID_PLOT_C                       9
#define ID_PLOT_CUSTOMIZATION           9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_metabolografTYPE            130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DIALOG1                     310
#define IDD_MAINLIST_CONFIG_DIALOG      310
#define IDB_MY                          317
#define IDB_ICONS_PNG                   321
#define IDD_PATIENT_DIALOG              324
#define IDD_AXIS_DIALOG                 327
#define IDB_MAIN_PNG                    329
#define IDD_BIGPLOT_DIALOG              330
#define IDD_SPLASH                      332
#define IDB_LOG                         334
#define IDB_LOGO                        334
#define IDD_DIALOG2                     335
#define IDD_CUSTOM_NUTRITION_DIALOG     335
#define IDB_ICONS_SMALL_PNG             337
#define IDD_POWER_STEP_DIALOG           340
#define IDD_VOLUME_ERROR_DIALOG         342
#define IDD_DIALOG3                     344
#define IDC_MAINLIST                    400
#define IDC_CURRVALUES                  401
#define IDC_HEADERS_CHECKLIST           500
#define IDC_TABCTRL                     501
#define ID_PLAYGROUNDWINDOW             600
#define IDC_VARIABLELIST                601
#define IDC_RICHEDITCTRL                602
#define IDC_OUTPUTLIST                  603
#define IDC_PLAYGROUNDCANVAS            604
#define ID_MAINPLOTWINDOW               605
#define ID_TIMERWINDOW                  606
#define IDOK_LISTDLG                    1000
#define IDC_TAB1                        1001
#define IDC_TAB2                        1002
#define IDC_PLOT_CUSTOMIZATION          1004
#define IDC_HEADER_EDIT                 1005
#define IDC_MEAN_EDIT                   1006
#define IDC_FIO_EDIT                    1006
#define IDC_AGE_EDIT                    1007
#define IDC_WEIGHT_EDIT                 1008
#define IDC_HEIGHT_EDIT                 1009
#define IDC_SEX_COMBO                   1010
#define IDC_WRIST_EDIT                  1011
#define IDC_BUTTON1                     1013
#define IDC_UNLOCK_BUTTON               1013
#define IDC_ADDBUTTON                   1013
#define IDC_CLEAR_BUTTON                1013
#define IDC_LIST1                       1014
#define IDC_DELETEBUTTON                1014
#define IDC_EDITLISTBUTTON              1015
#define IDC_TYPE1_RADIO                 1016
#define IDC_TYPE2_RADIO                 1017
#define IDC_MULTIVARLIST                1018
#define IDC_ONEVARLIST                  1019
#define IDC_TEXT_MULTI                  1020
#define IDC_TEXT_ONE                    1021
#define IDC_ONEAXISEDITBUTTON           1022
#define IDC_LEGENDEDIT                  1024
#define IDC_MINEDIT                     1025
#define IDC_VARCOMBO                    1026
#define IDC_MAXEDIT                     1027
#define IDC_SCALECOMBO                  1029
#define IDC_BIG_PLOT                    1030
#define IDC_AET                         1034
#define IDC_RADIO2                      1035
#define IDC_MOC                         1035
#define IDC_AT                          1036
#define IDC_LISTPLOT                    1037
#define IDC_COMBO1                      1039
#define IDC_EDIT_1                      1040
#define IDC_EDIT_2                      1041
#define IDC_EDIT_3                      1042
#define IDC_STATIC_1                    1044
#define IDC_STATIC_2                    1045
#define IDC_STATIC_3                    1046
#define IDC_EDIT5                       1047
#define IDC_PREVIEW                     1048
#define IDC_PREVIEW1                    1051
#define IDC_PREVIEW2                    1052
#define IDINFO                          1053
#define ID_EXPORT_MPK_BUTTON            1054
#define IDC_SLIDER1                     1060
#define IDC_EDITBOX                     1062
#define IDC_COMBO                       1064
#define IDC_COMBO2                      1065
#define IDC_MASKCOMBO                   1066
#define IDC_COMBO3                      1067
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_RECORD                       32771
#define ID_OPEN_FILE                    32772
#define ID_SAVE_FILE                    32773
#define ID_SAVE_FILE_AS                 32774
#define ID_SHOW_LIST_CONFIG             32775
#define ID_PATIENT_BUTTON               32776
#define ID_PLOT_CONFIG_BUTTON           32777
#define ID_CLEAR_PLOT                   32778
#define ID_DEFAULT_PLOT_BUTTON          32779
#define ID_BUTTON6                      32780
#define ID_BUTTON7                      32781
#define ID_BUTTON8                      32782
#define ID_BUTTON9                      32783
#define ID_BUTTON10                     32784
#define ID_BUTTON11                     32785
#define ID_BUTTON12                     32786
#define ID_ENLARGE_PLOT_BUTTON          32787
#define ID_UseExpiratoryVolume          32791
#define ID_Filter_TVolume               32792
#define ID_Filter_BrKoef                32793
#define ID_SHOW_PLOTDIALOG              32794
#define ID_RUN_SCRIPT                   32795
#define ID_SAVE_SCRIPT                  32796
#define ID_LOAD_SCRIPT                  32797
#define ID_NEW_SCRIPT                   32798
#define ID_SCRIPT_CONTEXT               32801
#define ID_SCRIPT_PROTOCOL              32802
#define ID_PLOT_CONTEXT                 32802
#define ID_PROTOCOL1                    32803
#define ID_PROTOCOL4                    32804
#define ID_PRO                          32805
#define ID_PROTOCOL3                    32805
#define ID_PROTOCOL_EXCEL               32806
#define ID_PROTOCOL_DATA                32807
#define ID_CURVALUES_VISIBLE            32808
#define ID_ENLARGE_PLOT_SHOW_DIALOG_BUTTON 32809
#define ID_START_TEST_BUTTON            32813
#define ID_END_TEST_BUTTON              32814
#define ID_LISTPLOTCONFIG_BUTTON        32815
#define ID_MPKMODE_BUTTON               32816
#define ID_ENLARGEBUTTON                32817
#define ID_CUSTOM_NUTRITIONBUTTON       32818
#define ID_UseInspiratoryVolume         32819
#define ID_UseMeanVolume                32820
#define ID_CUSTOM_NUTRITION             32821
#define ID_PROTOCOL_MPK                 32822
#define ID_VOLUME_FILTER_BUTTON         32823
#define ID_USE                          32824
#define ID_BUTTON3                      32825

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        346
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
